query getProduct($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    id
    productId: databaseId
    name
    description
    rawDescription: description(format: RAW)
    shortDescription
    ...ProductCategories
    ...Terms
    ...SimpleProduct
    ...ExternalProduct
    related(first: 5) {
      nodes {
        ...ShortProduct
      }
    }
    upsell(first: 5) {
      nodes {
        ...ShortProduct
      }
    }
    galleryImages {
      nodes {
        ...Image
      }
    }
  }
}

# Fragment definitions removed - they should be imported from separate files.
